language: r
cache: packages
os: linux

jobs:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache:
    - Rscript -e 'remotes::install_cran("textshaping"); remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'if (Sys.getenv("TRAVIS_REPO_SLUG", "") == "sahirbhatnagar/casebase") pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
      # script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true

r_packages:
  - knitr
  - ggplot2
  - gbm
  - glmnet
  - eha
  - covr
  - remotes

notifications:
  email:
    - turgeonmaxime@gmail.com
    - sahir.bhatnagar@gmail.com
