language: r
r:
  - release
  - devel
sudo: false
cache: packages

r_packages:
  - knitr
  - devtools
  - ggplot2
  - gbm
  - glmnet
  - eha
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    - turgeonmaxime@gmail.com
    - sahir.bhatnagar@gmail.com



