language: r
r:
  - release
  - devel
sudo: false
cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
  deploy:
    provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true

r_packages:
  - knitr
  - devtools
  - ggplot2
  - gbm
  - glmnet
  - eha
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    - turgeonmaxime@gmail.com
    - sahir.bhatnagar@gmail.com
