language: r
r:
  - release
  - devel
sudo: required

r_binary_packages:
  - knitr
  - ggplot2
  - eha

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    - maxime.turgeon@mail.mcgill.ca
    - sahir.bhatnagar@gmail.com
